name: pansy_accounts

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pansy_core:
    path: ../pansy_core

  pansy_arch_auth:
    path: ../pansy_arch_auth

  hive_flutter:
  flutter_bloc:

dev_dependencies:
  build_runner:
  freezed:
  injectable_generator:
  json_serializable:

  graphql_codegen:
    git:
      url: https://github.com/exeteres/graphql_codegen
      ref: main
      path: graphql_codegen
