projects:
  shetter:
    schema: lib/**/schema.graphql
    documents: lib/**/*.graphql

  accounts:
    schema: pansy_libraries/pansy_accounts/**/schema.graphql
    documents: pansy_libraries/pansy_accounts/**/*.graphql
