projects:
  shetter:
    schema: lib/**/schema.graphql
    documents: lib/**/*.graphql
    extensions:
      endpoints:
        default:
          url: https://api.pansy.dev/shetter-next/graphql

  accounts:
    schema: pansy_libraries/pansy_accounts/**/schema.graphql
    documents: pansy_libraries/pansy_accounts/**/*.graphql
    extensions:
      endpoints:
        default:
          url: https://api.pansy.dev/accounts/graphql
