include: package:pansy_lint/pansy_lint.yaml

analyzer:
  plugins:
    # - dart_code_metrics

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - "**/*.graphql.g.dart"
    - "**/initializer.config.dart"
    - "**/generated"
    - "**/*.gr.dart"
    - "**/*.al.dart"
    - "**/*.i18n.dart"

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    #  - avoid-non-null-assertion
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    #  - no-magic-number
    - no-object-declaration
    - prefer-trailing-comma
    - always-remove-listener
    #  - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-extracting-callbacks
    - prefer-intl-name
    - provide-correct-intl-args
