name: shetter_app
version: 1.0.0+1
publish_to: none
description: Shetter App written in Flutter

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.0-nullsafety.2
  normalize: 0.5.2

  intl:
  freezed_annotation:
  flutter_bloc:
  graphql:
  auto_localized:
  url_launcher:
  get_it:
  injectable:
  connectivity_plus:
  hive_flutter:
  get:
  simple_animations:
  flutter_markdown:
  flutter_scale_tap:
  auto_route:
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  index_generator:
  dart_code_metrics:
  auto_localized_generator:
  auto_route_generator:
  injectable_generator:

  graphql_codegen:
    git:
      url: https://github.com/exeteres/graphql_codegen
      ref: main
      path: graphql_codegen

  flutter_test:
    sdk: flutter

  ubuntu_font_flutter:

flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: packages/ubuntu_font_flutter/Ubuntu-R.ttf
        - asset: packages/ubuntu_font_flutter/Ubuntu-RI.ttf
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-B.ttf
          weight: 700
        - asset: packages/ubuntu_font_flutter/Ubuntu-BI.ttf
          weight: 700
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-L.ttf
          weight: 300
        - asset: packages/ubuntu_font_flutter/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-M.ttf
          weight: 500
        - asset: packages/ubuntu_font_flutter/Ubuntu-MI.ttf
          weight: 500
          style: italic
    - family: Ubuntu Mono
      fonts:
        - asset: packages/ubuntu_font_flutter/UbuntuMono-R.ttf
        - asset: packages/ubuntu_font_flutter/UbuntuMono-RI.ttf
          style: italic
        - asset: packages/ubuntu_font_flutter/UbuntuMono-B.ttf
          weight: 700
        - asset: packages/ubuntu_font_flutter/UbuntuMono-BI.ttf
          weight: 700
          style: italic
    - family: Ubuntu Condensed
      fonts:
        - asset: packages/ubuntu_font_flutter/Ubuntu-C.ttf

index_generator:
  filters:
    - black: .*\.g\.dart$
    - black: .*\.freezed\.dart$
  indexes:
    - path: lib/app

    - path: lib/core/domain
    - path: lib/core/infrastructure
    - path: lib/core/presentation

    - path: lib/features/posts/domain
    - path: lib/features/posts/infrastructure
    - path: lib/features/posts/presentation

    - path: lib/features/auth/domain
    - path: lib/features/auth/infrastructure
    - path: lib/features/auth/presentation
