name: shetter_app
version: 0.2.1
publish_to: none
description: Shetter App written in Flutter

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  url_launcher:
  simple_animations:
  auto_route:
  image_picker:

dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  index_generator:
  dart_code_metrics:
  auto_route_generator:
  injectable_generator:

  pansy_accounts:
    path: pansy_libraries/pansy_accounts

  graphql_codegen:
    git:
      url: https://github.com/exeteres/graphql_codegen
      ref: main
      path: graphql_codegen

  ubuntu_font_flutter:
  melos:

flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: packages/ubuntu_font_flutter/Ubuntu-R.ttf
        - asset: packages/ubuntu_font_flutter/Ubuntu-RI.ttf
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-B.ttf
          weight: 700
        - asset: packages/ubuntu_font_flutter/Ubuntu-BI.ttf
          weight: 700
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-L.ttf
          weight: 300
        - asset: packages/ubuntu_font_flutter/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-M.ttf
          weight: 500
        - asset: packages/ubuntu_font_flutter/Ubuntu-MI.ttf
          weight: 500
          style: italic
    - family: Ubuntu Mono
      fonts:
        - asset: packages/ubuntu_font_flutter/UbuntuMono-R.ttf
        - asset: packages/ubuntu_font_flutter/UbuntuMono-RI.ttf
          style: italic
        - asset: packages/ubuntu_font_flutter/UbuntuMono-B.ttf
          weight: 700
        - asset: packages/ubuntu_font_flutter/UbuntuMono-BI.ttf
          weight: 700
          style: italic
    - family: Ubuntu Condensed
      fonts:
        - asset: packages/ubuntu_font_flutter/Ubuntu-C.ttf

index_generator:
  filters:
    - black: .*\.g\.dart$
    - black: .*\.freezed\.dart$
    - black: initializer.config.dart
  indexes:
    - path: lib/app

    - path: lib/core/domain
    - path: lib/core/infrastructure
    - path: lib/core/presentation

    - path: lib/features/posts/domain
    - path: lib/features/posts/infrastructure
    - path: lib/features/posts/presentation

    # Pansy libraries

    - path: pansy_libraries/pansy_arch_core/lib/domain
    - path: pansy_libraries/pansy_arch_core/lib/infrastructure
    - path: pansy_libraries/pansy_arch_core/lib/presentation

    - path: pansy_libraries/pansy_arch_graphql/lib/domain
    - path: pansy_libraries/pansy_arch_graphql/lib/infrastructure

    - path: pansy_libraries/pansy_arch_auth/lib/domain
    - path: pansy_libraries/pansy_arch_auth/lib/infrastructure

    - path: pansy_libraries/pansy_core/lib/domain
    - path: pansy_libraries/pansy_core/lib/infrastructure
    - path: pansy_libraries/pansy_core/lib/presentation

    - path: pansy_libraries/pansy_accounts/lib/domain
    - path: pansy_libraries/pansy_accounts/lib/infrastructure
    - path: pansy_libraries/pansy_accounts/lib/presentation

    - path: pansy_libraries/pansy_ui/lib
      name: pansy_ui

    - path: pansy_libraries/pansy_localization/lib
      name: pansy_localization

cider:
  link_template:
    tag: https://github.com/pansydev/shetter_app/releases/tag/v%tag%
    diff: https://github.com/pansydev/shetter_app/compare/v%from%...v%to%
