name: shetter_app
version: 0.2.5
publish_to: none
description: Shetter App written in Flutter

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  url_launcher: ^6.1.4
  simple_animations: ^4.2.0
  auto_route: ^4.2.0
  image_picker: ^0.8.5+3

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  index_generator: ^3.3.0
  dart_code_metrics: ^4.16.0
  auto_route_generator: ^4.2.0
  dino_generator:
    git:
      url: https://github.com/pansydev/dino
      path: packages/dino_generator

  pansy_accounts:
    path: packages/pansy_accounts

  graphql_codegen: ^0.9.0

  ubuntu_font_flutter: ^0.0.1

  melos: ^2.5.0
  cider: ^0.1.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Ubuntu
      fonts:
        - asset: packages/ubuntu_font_flutter/Ubuntu-R.ttf
        - asset: packages/ubuntu_font_flutter/Ubuntu-RI.ttf
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-B.ttf
          weight: 700
        - asset: packages/ubuntu_font_flutter/Ubuntu-BI.ttf
          weight: 700
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-L.ttf
          weight: 300
        - asset: packages/ubuntu_font_flutter/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-M.ttf
          weight: 500
        - asset: packages/ubuntu_font_flutter/Ubuntu-MI.ttf
          weight: 500
          style: italic
    - family: Ubuntu Mono
      fonts:
        - asset: packages/ubuntu_font_flutter/UbuntuMono-R.ttf
        - asset: packages/ubuntu_font_flutter/UbuntuMono-RI.ttf
          style: italic
        - asset: packages/ubuntu_font_flutter/UbuntuMono-B.ttf
          weight: 700
        - asset: packages/ubuntu_font_flutter/UbuntuMono-BI.ttf
          weight: 700
          style: italic
    - family: Ubuntu Condensed
      fonts:
        - asset: packages/ubuntu_font_flutter/Ubuntu-C.ttf

index_generator:
  exclude:
    - "**.g.dart"
    - "**.gr.dart"
    - "**.freezed.dart"
    - initializer.config.dart

  indexes:
    - path: lib/app

    - path: lib/core/domain
    - path: lib/core/infrastructure
    - path: lib/core/presentation

    - path: lib/modules/posts/domain
    - path: lib/modules/posts/infrastructure
    - path: lib/modules/posts/presentation

    # Pansy libraries

    - path: packages/pansy_arch_core/lib/domain
    - path: packages/pansy_arch_core/lib/infrastructure
    - path: packages/pansy_arch_core/lib/presentation

    - path: packages/pansy_arch_graphql/lib/domain
    - path: packages/pansy_arch_graphql/lib/infrastructure

    - path: packages/pansy_arch_auth/lib/domain
    - path: packages/pansy_arch_auth/lib/infrastructure

    - path: packages/pansy_core/lib/domain
    - path: packages/pansy_core/lib/infrastructure
    - path: packages/pansy_core/lib/presentation

    - path: packages/pansy_accounts/lib/domain
    - path: packages/pansy_accounts/lib/infrastructure
    - path: packages/pansy_accounts/lib/presentation

    - path: packages/pansy_ui/lib
      name: pansy_ui

    - path: packages/pansy_localization/lib
      name: pansy_localization

cider:
  link_template:
    tag: https://github.com/pansydev/shetter_app/releases/tag/v%tag%
    diff: https://github.com/pansydev/shetter_app/compare/v%from%...v%to%
