targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
          scalars:
            UUID:
              type: String
            Long:
              type: int
            URL:
              type: String
            DateTime:
              type: String
            Upload:
              type: dynamic
