name: pansy_accounts

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pansy_core:
    path: ../pansy_core

  pansy_arch_auth:
    path: ../pansy_arch_auth

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  dino_generator:
    git:
      url: https://github.com/pansydev/dino
      path: packages/dino_generator
  json_serializable: ^6.2.0

  graphql_codegen: ^0.9.0
