name: pansy_arch_auth

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pansy_arch_core:
    path: ../pansy_arch_core

dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
