name: pansy_core

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pansy_arch_core:
    path: ../pansy_arch_core

  pansy_arch_graphql:
    path: ../pansy_arch_graphql

  pansy_ui:
    path: ../pansy_ui

dev_dependencies:
  build_runner:
  freezed:
  json_serializable:
  injectable_generator:
