name: pansy_core

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pansy_arch_core:
    path: ../pansy_arch_core

  pansy_arch_graphql:
    path: ../pansy_arch_graphql

  pansy_ui:
    path: ../pansy_ui

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  dino_generator:
    git:
      url: https://github.com/pansydev/dino
      path: packages/dino_generator
