name: pansy_arch_core

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider:
  fpdart:
  freezed_annotation:
  i18n:

  # TODO replace get_it and injectable with own di container
  get_it:
  injectable:

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed:
  build_runner:
  json_serializable:
  injectable_generator:
  index_generator:
