name: pansy_ui

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_color: ^2.0.0
  cached_network_image: ^3.2.1
  blurhash_dart: ^1.1.0
  i18n: ^3.4.1
  fluttertoast: ^8.0.9

dev_dependencies:
  build_runner: ^2.1.11
