name: pansy_arch_graphql

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  pansy_arch_core:
    path: ../pansy_arch_core

  normalize: ^0.6.0
  connectivity_plus: ^2.3.5
  graphql: ^5.1.1
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  dino_generator:
    git:
      url: https://github.com/pansydev/dino
      path: packages/dino_generator
  json_serializable: ^6.2.0
  graphql_codegen: ^0.9.0
