name: test

on: [push, pull_request]

jobs:
  build:
    name: Upload coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Code generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # - name: Run tests
      #   run: flutter test --coverage

      # - name: Install lcov
      #   run: sudo apt-get install -y lcov

      # - name: Remove generated files from code coverage report
      #   run: lcov --remove coverage/lcov.info 'lib/*/*.freezed.dart' 'lib/*/*.g.dart' 'lib/*/*.part.dart' 'lib/generated/*.dart' 'lib/generated/*/*.dart' -o coverage/lcov.info

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1.2.1
      #   with:
      #     file: coverage/lcov.info
      #     token: "${{ secrets.CODECOV_TOKEN }}"
